# Site settings
title: Puzzled 2024
email: puzzled@kcl.ac.uk
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://davidkmarzagao.github.io/puzzled/" # the base hostname & protocol for your site

instagram_username: kclpuzzled
twitter_username:
github_username:

# Build settings
markdown: kramdown
